// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetApiCompetitionsCurrentData, GetApiCompetitionsCurrentResponse, GetApiDashboardData, GetApiDashboardResponse } from './types.gen';

export const client = createClient(createConfig());

export const getApiCompetitionsCurrent = <ThrowOnError extends boolean = false>(options?: Options<GetApiCompetitionsCurrentData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiCompetitionsCurrentResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/competitions/current'
    });
};

export const getApiDashboard = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiDashboardResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/dashboard'
    });
};