// This file is auto-generated by @hey-api/openapi-ts

import type { GetApiCompetitionsCurrentResponse, GetApiDashboardResponse } from './types.gen';

const competitionModelSchemaResponseTransformer = (data: any) => {
    if (data.startedOn) {
        data.startedOn = new Date(data.startedOn);
    }
    return data;
};

export const getApiCompetitionsCurrentResponseTransformer = async (data: any): Promise<GetApiCompetitionsCurrentResponse> => {
    data = data.map((item: any) => {
        return competitionModelSchemaResponseTransformer(item);
    });
    return data;
};

const dashboardModelSchemaResponseTransformer = (data: any) => {
    if (data.competition) {
        data.competition = competitionModelSchemaResponseTransformer(data.competition);
    }
    return data;
};

export const getApiDashboardResponseTransformer = async (data: any): Promise<GetApiDashboardResponse> => {
    data = dashboardModelSchemaResponseTransformer(data);
    return data;
};